### PR TITLE
Using the latest version of simplenfl!

### PR DESCRIPTION
**Pull request by PipeWarp**

### CODE REVIEW

**Comment by ngawung** [comment]
yeah.. i would like to use the latest version...
but somehow it failed to build in my env... idk why... 
i still new in c/c++ so i dont know whats wrong... this low level programming confuse me...
anyway i just need touch and sound from your simpleNFL... so as long as it works im fine xD

**Comment by PipeWarp** [comment]
Sorry for the late reply, thanks for the info!
I'm currently fixing this!

**Comment by ngawung** [comment]
awesome.... im already using your latest version now.... im also slightly modify it to support c++
and adding held and release phase for touch... im planning to do pr on your repo...

**Comment by PipeWarp** [comment]
Make a pull request on the repo if you want, I'll merge it in and credit you!

**Comment by ngawung** [comment]
i was thinking to do pr... but im not sure if my code also work on c since it using c++
like i said... im not quite familiar yet with c stuff... you may know better than me

this is where i put my modified simplenfl
https://github.com/ngawung/turnip-project/tree/master/include/lib

**Pull request closed without merging**
